// One-command onboarding for a fresh clone: `pnpm setup`.
// Walks env -> auth -> scan -> score -> gen-droplist, then prints the deploy + secret commands.
// Each step shells out to the existing pnpm commands, so this is just the guided glue.
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import readline from "node:readline";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const p = (...s) => path.join(root, ...s);
const log = (m) => console.log(`\n\x1b[1m▶ ${m}\x1b[0m`);
const ok = (m) => console.log(`  \x1b[32m✓\x1b[0m ${m}`);
const warn = (m) => console.log(`  \x1b[33m!\x1b[0m ${m}`);

function ask(q) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((res) => rl.question(q, (a) => { rl.close(); res(a.trim()); }));
}
function run(cmd) {
  execSync(cmd, { cwd: root, stdio: "inherit" });
}
function parseEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, "utf8").split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
  return out;
}

console.log("\n\x1b[1mx-ratio-agent setup\x1b[0m — get your X following down to a target, on autopilot.\n");

// ── 1. Environment ────────────────────────────────────────────────────────────
log("Step 1/6 — environment");
if (!fs.existsSync(p(".env"))) {
  fs.copyFileSync(p(".env.example"), p(".env"));
  warn("Created .env from .env.example.");
}
const env = parseEnv(p(".env"));
const required = ["BROWSERBASE_API_KEY", "BROWSERBASE_PROJECT_ID", "X_HANDLE", "ANTHROPIC_API_KEY"];
const missing = required.filter((k) => !env[k]);
if (missing.length) {
  warn(`Fill these in .env before continuing: ${missing.join(", ")}`);
  console.log("  - Browserbase key + project id: https://www.browserbase.com/settings");
  console.log("  - Anthropic key (for relevance scoring): https://console.anthropic.com/");
  console.log("  - X_HANDLE: your username without the @");
  console.log("\nEdit .env, then re-run `pnpm setup`.");
  process.exit(1);
}
ok("All required env vars present.");

// config.local.ts (personal Context/handle) — create from example if missing
if (!fs.existsSync(p("functions", "config.local.ts"))) {
  fs.copyFileSync(p("functions", "config.local.example.ts"), p("functions", "config.local.ts"));
  ok("Created functions/config.local.ts from the example.");
}

// ── 2. Auth (create a Browserbase Context holding your X login) ─────────────────
log("Step 2/6 — log into X (creates a persisted Browserbase Context)");
const ctxFile = p("data", "context.json");
let haveCtx = fs.existsSync(ctxFile);
if (haveCtx) {
  const ans = await ask("  A saved Context already exists. Re-run login? [y/N] ");
  haveCtx = ans.toLowerCase() !== "y";
}
if (!haveCtx) {
  console.log("  A Live View URL will print — open it, log into X by hand, then press ENTER there.");
  run("pnpm auth");
}

// Sync config.local.ts from the persisted Context id + your handle
if (fs.existsSync(ctxFile)) {
  const contextId = JSON.parse(fs.readFileSync(ctxFile, "utf8")).contextId;
  const handle = (env.X_HANDLE || "").replace(/^@/, "");
  const body =
    "// LOCAL + GITIGNORED. Generated by `pnpm setup`.\n" +
    `export const CONTEXT_ID = ${JSON.stringify(contextId)};\n` +
    `export const X_HANDLE = ${JSON.stringify(handle)};\n`;
  fs.writeFileSync(p("functions", "config.local.ts"), body);
  ok(`Wrote functions/config.local.ts (Context ${contextId.slice(0, 8)}…, @${handle}).`);
} else {
  warn("No data/context.json found — auth may not have completed. Re-run `pnpm setup`.");
  process.exit(1);
}

// ── 3–5. Harvest, score, generate the target list ──────────────────────────────
log("Step 3/6 — harvest your follow graph");
run("pnpm scan");
log("Step 4/6 — score every non-mutual against interest-profile.md");
if (!fs.existsSync(p("interest-profile.md"))) {
  fs.copyFileSync(p("interest-profile.example.md"), p("interest-profile.md"));
  warn("Created interest-profile.md from the example — edit it to your interests for better scoring.");
}
run("pnpm score");
log("Step 5/6 — generate the Function's target list");
run("node scripts/gen-droplist.mjs");

// ── 6. Deploy instructions ──────────────────────────────────────────────────────
log("Step 6/6 — deploy the daily grind");
console.log(`
  Everything local is ready. To go live:

    cd functions
    npx bb publish main.ts          # builds + prints your Function ID — copy it

  Then wire the GitHub Actions cron (from the repo root):

    gh secret set BROWSERBASE_API_KEY --body "$BROWSERBASE_API_KEY"
    gh secret set BB_FUNCTION_ID      --body "<FUNCTION_ID_FROM_PUBLISH>"

  The workflow in .github/workflows/daily-unfollow.yml pokes the Function 3×/day.
  See functions/DEPLOY.md for the full runbook.
`);
ok("Setup complete.");
